name: RT-Client
version: 0.00_02
abstract: A client of RT from Best Practical Solutions
author: Autrijus Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
requires:
  XML::Simple: 0.01
  XML::Atom: 0.07
  URI: 0
  Spiffy: 0.16
  LWP::Authen::Wsse: 0
  Digest::MD5: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.33
