name: RT-Client
version: 0.00_01
abstract: A client of RT from Best Practical Solutions
author: Autrijus Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
requires:
  XML::Atom: 0.07
  LWP::Authen::Wsse: 0.01
  Spiffy: 0.16
  Filter::Include: 1.4
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.33
